# NTPAC stack with Cassandra repository

version: '3.5'

services:
  lighthouse:
    image: docker.nesad.fit.vutbr.cz/lighthouse:latest
    environment:
      - NTPAC_NODE=lighthouse
    deploy:
      placement:
        constraints:
          - node.labels.lighthouse == true

  reassembler:
    image: docker.nesad.fit.vutbr.cz/reassembler:latest
    environment:
      - NTPAC_SEED_NODE=lighthouse:7070
    depends_on:
      - lighthouse
      - cassandra-seed
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.reassembler == true
    command: --cassandra-repository --cassandra-keyspace=ntpac --cassandra-contactpoint=cassandra-seed

  cassandra-seed:
    image: docker.nesad.fit.vutbr.cz/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=tasks.cassandra-seed
      - LOCAL_JMX=no
    command: cassandra -f -Dcom.sun.management.jmxremote.authenticate=false
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cassandra == true

  cassandra:
    image: docker.nesad.fit.vutbr.cz/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=tasks.cassandra-seed
    command: /ntpac-docker-entrypoint.sh cassandra -f -Dcassandra.consistent.rangemovement=false
    depends_on:
      - cassandra-seed
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.cassandra == true

networks:
  default:
    attachable: true